### ISSUE TITLE
index首页-字体问题

### ISSUE THREAD

**Issue by kimicuyf** [html5-13/staticsite#108]
字体大小、颜色与设计图不符：
1.
![issue1](https://f.cloud.github.com/assets/3362014/102178/8fbf0d34-6913-11e2-8f35-295d1930b010.png)
2.
![issue](https://f.cloud.github.com/assets/3362014/102176/4d4f3988-6913-11e2-8f1e-bcc240c1056f.png)

**Comment by huangxianda080** [comment]
已修改
