### ISSUE TITLE
index首页-图片背景问题

### ISSUE THREAD

**Issue by kimicuyf** [html5-13/staticsite#109]
截图质量差，且与设计图反差较大：
1.实习生活动
![issue2](https://f.cloud.github.com/assets/3362014/102182/05c0acae-6914-11e2-858a-5013ff8d7b10.png)
2.banner背景
![issue3](https://f.cloud.github.com/assets/3362014/102185/1ff3d222-6914-11e2-94e8-c3894ab5b293.png)

**Comment by huangxianda080** [comment]
已更换图片
