### ISSUE TITLE
th-pl   字体颜色大小不一样

### ISSUE THREAD

**Issue by Zhouwen** [html5-13/staticsite#115]
![ 8](https://f.cloud.github.com/assets/3367367/102195/813655c2-6915-11e2-937a-a8ef90a0d644.png)
![ 9](https://f.cloud.github.com/assets/3367367/102198/c0e5542a-6915-11e2-91f8-170b38bad2de.png)
原图

**Comment by gaojie0620** [comment]
重新取色，修改
