### ISSUE TITLE
th-pl   字体颜色大小都不一样

### ISSUE THREAD

**Issue by Zhouwen** [html5-13/staticsite#118]
![ 10](https://f.cloud.github.com/assets/3367367/102203/f5308376-6915-11e2-980a-5c175d42205b.png)
![ 11](https://f.cloud.github.com/assets/3367367/102204/fc9bf30c-6915-11e2-86ed-b700a2c4270a.png)
原图

**Comment by gaojie0620** [comment]
右侧组件人员更改color就行
