### ISSUE TITLE
J_il之第四个小问题

### ISSUE THREAD

**Issue by huangxianda080** [html5-13/staticsite#121]
![a](https://f.cloud.github.com/assets/3366984/102222/370f5406-6917-11e2-84ee-deddf8d32af4.jpg)
动态改招聘
![s](https://f.cloud.github.com/assets/3366984/102223/3fb4bab0-6917-11e2-8c8d-9e79a4a6593c.jpg)

**Comment by rogueduola** [comment]
已改好，谢谢
