### ISSUE TITLE
底部组件实现方式不对

### ISSUE THREAD

**Issue by smallnewer** [html5-13/staticsite#146]
1.
![ 2013-01-28 3 06 40](https://f.cloud.github.com/assets/1390940/102253/4de5aaca-6919-11e2-9b40-559239952a92.png)
图标不应该用img实现，文字应该用h3-h4
2.
![ 2013-01-28 3 09 24](https://f.cloud.github.com/assets/1390940/102262/afd8622c-6919-11e2-947d-7be2be10f963.png)
圆点应该是由4个标签实现，而不是一张背景图。
3.友情链接的每个链接，hover时不需要加下划线
4.有关标签错误，仔细检查。
5.go to top 没必要放图片，写给a标签的背景即可
6.整个网站通用的底部，class命名建议foot开头，或者ft，footer等，通常都是这种写法。不建议page-bot.

**Comment by a469453770** [comment]
重做了
