### ISSUE TITLE
th_ca html中书写混乱

### ISSUE THREAD

**Issue by rogueduola** [html5-13/staticsite#34]
html没有换行且有空行
![question21](https://f.cloud.github.com/assets/3366998/102060/4edeff2a-690b-11e2-877f-af99159ee7c9.png)
空行
![question22](https://f.cloud.github.com/assets/3366998/102071/ef1de85c-690b-11e2-825a-c4e9b4a93c39.png)
![question23](https://f.cloud.github.com/assets/3366998/102072/6c0384a8-690c-11e2-8f66-4d07ce046573.png)
![question24](https://f.cloud.github.com/assets/3366998/102082/524f4e7e-690d-11e2-87f2-163e08165a11.png)
同时部分缩进也有问题

**Comment by wangjing87654321** [comment]
改了缩进
