### ISSUE TITLE
c-dl    距离不一样

### ISSUE THREAD

**Issue by Zhouwen** [html5-13/staticsite#41]
![ 2 1](https://f.cloud.github.com/assets/3367367/102087/a9adc47a-690d-11e2-81d4-3f2e46068a04.png)原图
![ 2](https://f.cloud.github.com/assets/3367367/102093/1319d6b0-690e-11e2-8b80-a8e719fa6ee3.png)

**Comment by gaojie0620** [comment]
发错了，c_dl中没有这个图
