### ISSUE TITLE
c_sa html的img标签alt里没内容同时有部分空行

### ISSUE THREAD

**Issue by rogueduola** [html5-13/staticsite#59]
![question1](https://f.cloud.github.com/assets/3366998/102114/d5e56b86-690f-11e2-9c59-b6ec67505972.png)
![question2](https://f.cloud.github.com/assets/3366998/102119/ff69f850-690f-11e2-8af9-105c49715c76.png)
![question3](https://f.cloud.github.com/assets/3366998/102122/50cdac6e-6910-11e2-9397-8339210101c5.png)

**Comment by huangxianda080** [comment]
已去除
