### ISSUE TITLE
choice.html-博看动态模块-图片右下角没导航

### ISSUE THREAD

**Issue by KavinHan** [html5-13/staticsite#91]
设计图是这样的
![teacher-2](https://f.cloud.github.com/assets/3361694/102160/818ca40c-6912-11e2-9685-b70d7e3fc4b5.JPG)
实际上是这样的
![teacher-3](https://f.cloud.github.com/assets/3361694/102162/93ad067c-6912-11e2-9912-e5434cf7170a.JPG)

**Comment by Zhouwen** [comment]
已改完
